# Generated by Django 5.0 on 2024-04-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="Phone_No",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
