# Generated by Django 5.0 on 2024-04-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_rename_deliveryaddress_deliveryinfo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryinfo",
            old_name="full_name",
            new_name="Delivery_full_name",
        ),
    ]
