# Generated by Django 5.0 on 2024-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_rename_full_name_deliveryinfo_delivery_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryinfo",
            name="Delivery_date",
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deliveryinfo",
            name="Delivery_time",
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
    ]
