# Generated by Django 5.0 on 2024-04-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_deliveryinfo_delivery_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_address",
            new_name="delivery_info",
        ),
    ]
