# Generated by Django 5.0.4 on 2024-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_delete_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='Delivery_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='Delivery_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
