# Generated by Django 5.0 on 2024-04-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Unnapp", "0004_profile_delete_signin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="address1",
            new_name="address",
        ),
    ]
