# Generated by Django 5.0 on 2024-04-19 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Unnapp", "0006_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="cart_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartitems",
                to="Unnapp.cart",
            ),
        ),
    ]
