# Generated by Django 5.0 on 2024-04-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Unnapp", "0007_cartitem_cart_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="items",
            new_name="item",
        ),
    ]
