# Generated by Django 5.0 on 2024-04-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Unnapp", "0008_rename_items_cart_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="item",
            new_name="items",
        ),
    ]
