# Generated by Django 5.0 on 2024-04-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Unnapp", "0009_rename_item_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
