# Generated by Django 5.0.4 on 2024-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unnapp', '0013_deliverystatus_user_alter_deliverystatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverystatus',
            options={'verbose_name_plural': 'DeliveryStatus'},
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
